<!-- upper.jsp -->
<%@ include file="../upper.jsp" %>

<%-- This is comment.
	 There is include directive bloew.
	 									--%>

<!-- This is HTML comment.
	 Upper link is included.	-->

<%! // declaration of the function
	int factorial(int x)
	{
		if (x > 1)
			return x*factorial(x-1);
		else
			return 1;
	}
	
	// declaration of the variable
	int temp;
%>

<%
	// java code in scriptlet tag
	temp = 10;
%>
The Factorial of the <%= temp %> <!-- generated by expression tag --> is 
<%= factorial(temp) %>.

<!-- footer.html -->
<%@ include file="../footer.html" %>
