
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;

public class IncludedPage extends HttpServlet {
    
    public void doGet(HttpServletRequest request,
                      HttpServletResponse response)
        throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        out.println("<font color=\"blue\">");
        out.println("<br><br><b>This table is generated by IncludedPage<b>");
        out.println("<table border=\"0\" cellpadding=\"5\">");
        out.println("<tr><td bgcolor=\"#CCFFFF\">Context Path</td><td>");
        out.println(request.getContextPath() + "</td></tr>");
        out.println("<tr><td bgcolor=\"#CCFFFF\">Servlet Path</td><td>");
        out.println(request.getServletPath() + "</td></tr>");
        out.println("<tr><td bgcolor=\"#CCFFFF\">Path Info</td><td>");
        out.println(request.getPathInfo() + "</td></tr>");
        out.println("<tr><td bgcolor=\"#CCFFFF\">Request URI</td><td>");
        out.println(request.getRequestURI() + "</td></tr>");
        out.println("<tr><td bgcolor=\"#CCFFFF\">Query String</td><td>");
        out.println(request.getQueryString() + "</td></tr>");

        Enumeration enum = request.getParameterNames();
        while (enum.hasMoreElements()) {
            String name = (String)enum.nextElement();
            String value = request.getParameter(name);
            out.println("<tr><td bgcolor=\"#CCFFFF\">Parameter: " + name + "</td><td>");
            out.println(value + "</td></tr>");
        }

        enum = request.getAttributeNames();
        while (enum.hasMoreElements()) {
            String name = (String)enum.nextElement();
      	    Object value = request.getAttribute(name);
            out.println("<tr><td bgcolor=\"#CCFFFF\">Attribute: " + name + "</td><td>");
            out.println(value + "</td></tr>");
        }
	request.removeAttribute("included servlet");
        out.println("</table>");
        out.println("</font>");
    }
}
