<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">
<script>

<input-symbol key="explosive"   class="jeus.tool.webadmin.component.Explosive" required="yes"/>

<let key="explode">
	explode
</let>

<body>

function ${explode}(){
    <if expression="explosive.message != null">
        alert('${explosive.message}');
    </if>

    <foreach key="target" expression="explosive.targetSet">
        ${target}.location.href = "${explosive.getHref(target)}";
    </foreach>
}

</body>

</script>
